# Site settings

remote_theme: jekyll/minima
exclude: [bundle]

title: Tcheuling de Meudon
email: tcheulingdemeudon@orange.fr
description: >
  Méditation à Meudon - Tcheuling de Meudon (à 10km de Paris), lieu dédié à
  l'enseignement et à la pratique de la méditation dans la tradition du bouddhisme
  tibétain sous la direction spirituelle de Lama Tsultrim. Affilié à
  Bodhicharya-France.
baseurl: ""
url: "https://tcheulingdemeudon.github.io"

header_pages:
  - index.md
  - comment-venir.md
  - adhesion.md
  - priere-lignee.md
  
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

